# Default FTXPy configuration file for Perlmutter

#   _____                   _   
#  |_   _|                 | |  
#    | |  _ __  _ __  _   _| |_ 
#    | | | '_ \| '_ \| | | | __|
#   _| |_| | | | |_) | |_| | |_ 
#  |_____|_| |_| .__/ \__,_|\__|
#              | |              
#              |_|              

#
# Time control parameters
#

[input.parameters.INIT_TIME]
description = "The start time of the simulation"
value = 0.0

[input.parameters.END_TIME]
description = "The end time of the simulation"
value = 10

[input.parameters.LOOP_TIME_STEP]
description = "The initial length of a loop"
value = 0.05

[input.parameters.LOOP_TS_FACTOR]
description = "The multiplication factor for the loop length"
value = 2

[input.parameters.LOOP_TS_NLOOPS]
description = "Multiply 'LOOP_TIME_STEP' by 'LOOP_TS_FACTOR' every 'LOOP_TS_NLOOPS' loops"
value = 1

[input.parameters.START_MODE]
description = "Start mode of the simulation ('INIT' or 'RESTART')"
value = "INIT"

[input.parameters.LOOP_N]
description = "FTX loop number"
value = 0

[input.parameters.XOLOTL_MAX_TS]
description = "A limit on how much to increase Xolotl's max time step"
value = 0.001

[input.parameters.XOLOTL_NUM_TRIES]
description = "Number of times to try to run Xolotl before giving up"
value = 3

[input.parameters.time_decimal]
description = "Round each time to the given time decimal"
value  = 14

#
# PETSc parameters
#

[input.parameters.start_stop]
description = "(?) A parameter in PETSc, should be ~'LOOP_TIME_STEP'/10"
value = 0.005

[input.parameters.ts_adapt_dt_max]
description = "Initial value of time step in PETSc"
value = 1e-5

[input.parameters.ts_atol]
description = "Absolute tolerance in PETSc"
value = 1e-5

[input.parameters.ts_rtol]
description = "Relative tolerance in PETSc"
value = 1e-5

[input.parameters.ts_adapt_clip]
description = "Sets the admissible decrease/increase factor in step size in the time step adapter"
value = "'0.1,1.1'"

#
# Fidelity parameters
#

[input.parameters.gridParam]
description = "The size of the computational domain"
value = 256

[input.parameters.netParam]
description = "Parameters related to the network size (nHe nD nT maxVSize nInterstitials phaseCut)"
value = "8 0 0 250 6 false"

[input.parameters.grouping]
description = "Parameters related to the grouping (grouping = groupHeV groupHe groupV; grouping ON: groupHeV < MaxVSize)"
value = "31 4 4"

[input.parameters.nImpacts]
description = "The number of particles to use"
value = 100000

#
# F-Tridyn parameters
#

[input.parameters.SBV_W]
description = "Surface binding energy of W [eV]"
value = 8.78
lower = 8.68
upper = 12

[input.parameters.EF_W]
description = "Cutoff energy of W [eV]"
value = 3
lower = 2.7
upper = 3.3

[input.parameters.EF_He]
description = "Cutoff energy of He [eV]"
value = 0.1
lower = 0.09
upper = 1.1

[input.parameters.E0_He]
description = "Beam energy [eV]"
value = 250
lower = 240
upper = 300

[input.parameters.ALPHA0_He]
description = "Incident angle [degrees]"
value = 0
lower = 0
upper = 30

#
# Xolotl parameters
#

[input.parameters.lattice]
description = "The length of the lattice side [nm]"
value = 0.317
lower = 0.316
upper = 0.318

[input.parameters.impurityRadius]
description = "The radius of the main impurity [nm]"
value = 0.3
lower = 0.27
upper = 0.33

[input.parameters.biasFactor]
description = "Interstitial bias factor (interstitial clusters have a larger strain field) [-]"
value = 1.15
lower = 1.035
upper = 1.265

[input.parameters.initialV]
description = "The initial concentration of vacancies in the material [#/nm3]"
value = 1e-18
lower = 1e-19
upper = 1e-17
log10_transform = "true"

[input.parameters.voidPortion]
description = "The fraction of the computational domain that is void"
value = 0.0

[input.parameters.burstingFactor]
description = "Multiplication constant for the bursting rate [-]"
value = 2e8
lower = 1e2
upper = 1e9
log10_transform = "true"

[input.parameters.burstingDepth]
description = "The depth after which there is an exponential decrease in the probability of bursting [nm]"
value = 10
lower = 1
upper = 20

[input.parameters.He1]
description = "Migration energy threshold (above which the diffusion will be ignored) for He1 clusters [eV]"
value = 0.13
lower = 0.11
upper = 0.25

[input.parameters.He2]
description = "Migration energy threshold (above which the diffusion will be ignored) for He2 clusters [eV]"
value = 0.2
lower = 0.2
upper = 0.3

[input.parameters.He3]
description = "Migration energy threshold (above which the diffusion will be ignored) for He3 clusters [eV]"
value = 0.25
lower = 0.25
upper = 0.4

[input.parameters.He4]
description = "Migration energy threshold (above which the diffusion will be ignored) for He4 clusters [eV]"
value = 0.2
lower = 0.15
upper = 0.5

[input.parameters.He5]
description = "Migration energy threshold (above which the diffusion will be ignored) for He5 clusters [eV]"
value = 0.12
lower = 0.1
upper = 0.2

[input.parameters.He6]
description = "Migration energy threshold (above which the diffusion will be ignored) for He6 clusters [eV]"
value = 0.3
lower = 0.3
upper = 0.45

[input.parameters.He7]
description = "Migration energy threshold (above which the diffusion will be ignored) for He7 clusters [eV]"
value = 0.4
lower = 0.3
upper = 0.45

[input.parameters.V1]
description = "Migration energy threshold (above which the diffusion will be ignored) for V1 clusters [eV]"
value = 1.3
lower = 1.1
upper = 1.5

#
# Simulation management parameters
#
[input.parameters.SIM_NAME]
description = "The name of this simulation"
value = "FTX UQ simulation"

[input.parameters.SIM_ROOT]
description = "The root directory for this simulation"
value = "$PWD"

#
# Case-dependent parameters
#

[input.parameters.inputEnergy_He]
description = "Flag to determine if the input energies for He are read from a distribution file (< 0) of if the given values are used (>= 0)"
value = "{E0_He}"

[input.parameters.inputEnergy_W]
description = "Flag to determine if the input energies for W are read from a distribution file (< 0) of if the given values are used (>= 0)"
value = 0.0

[input.parameters.inputAngle_He]
description = "Flag to determine if the input angles for He are read from a distribution file (< 0) of if the given values are used (>= 0)"
value = "{ALPHA0_He}"

[input.parameters.inputAngle_W]
description = "Flag to determine if the input angles for W are read from a distribution file (< 0) of if the given values are used (>= 0)"
value = 0.0

[input.parameters.tempParam]
description = "Parameter in the constanst temperature model"
value = 1093.0

[input.parameters.flux]
description = "Value of the flux in gitrOut.txt"
value = 5.4e22

[input.parameters.fluxFraction_He]
description = "Value of the flux fraction of He in gitrOut.txt"
value = 1

[input.parameters.fluxFraction_W]
description = "Value of the flux fraction of W in gitrOut.txt"
value = 0.00293159784018

[input.parameters.GITRoutput_dir]
description = "Location of the GITR output directory"
value = "GITRoutput/PISCES"

#
# Parallel processing parameters
#
[input.parameters.NPROC]
description = "Number of processors to use for Xolotl"
value = 128

[input.parameters.task_ppn]
description = "Number of processors per node for Xolotl, ideally NPROC/task_ppn = number of nodes"
value = 128

[input.parameters.FTMPI_NODES]
description = "Number of nodes to use for F-Tridyn"
value = 1

[input.parameters.FTMPI_PPN]
description = "Number of processes per node to use for F-Tridyn"
value = 128

#
# Machine
#
[input.parameters.MACHINE]
description = "Name of this machine"
value = "PERLMUTTER"

#
# Case-dependent parameters
#

[input.cases.PISCES.parameters]

[input.cases.ITER-He.parameters]
gridParam=367
inputEnergy_He = -1.0
inputEnergy_W = -1.0
inputAngle_He = -1.0
inputAngle_W = -1.0
tempParam = 343.0
flux = 3.49285e+20
fluxFraction_He = 9.978853e-1
fluxFraction_W = 2.114695e-3
GITRoutput_dir = "GITRoutput/ITER-He/gitr16"

#
# Default location of the source files
#

[input]
source = "${CFS}/atom/users/${USER}/ips-examples/iterative-xolotlFT-UQ"

#   ____        _       _                   _       _   
#  |  _ \      | |     | |                 (_)     | |  
#  | |_) | __ _| |_ ___| |__  ___  ___ _ __ _ _ __ | |_ 
#  |  _ < / _` | __/ __| '_ \/ __|/ __| '__| | '_ \| __|
#  | |_) | (_| | || (__| | | \__ \ (__| |  | | |_) | |_ 
#  |____/ \__,_|\__\___|_| |_|___/\___|_|  |_| .__/ \__|
#                                            | |        
#                                            |_|        

#
# Default SLURM settings
#

[batchscript.slurm_settings]
job_name = "ftx_job"
account = "m1709"
output = "log.slurm.stdOut"
qos = "regular"
constraints = "cpu"
min_nodes = 1
time_limit = 720

#
# Default list of commands to run
#

[batchscript]
commands = [
    "source activate ftx",
    "module load PrgEnv-cray cray-python",
    "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/gcc/11.2.0/snos/lib64",
    "export OMP_PLACES=threads",
    "export OMP_PROC_BIND=spread",
    "ips.py --config=ips.ftx.config --platform=conf.ips.perlmutter --log=log.framework 2>>log.stdErr 1>>log.stdOut"
]

#   _____            __ _ _           
#  |  __ \          / _(_) |          
#  | |__) | __ ___ | |_ _| | ___  ___ 
#  |  ___/ '__/ _ \|  _| | |/ _ \/ __|
#  | |   | | | (_) | | | | |  __/\__ \
#  |_|   |_|  \___/|_| |_|_|\___||___/
                                    
#
# Default debug profile
#

[profiles.debug.input.parameters]
END_TIME = 2e-4
LOOP_TIME_STEP = 1e-4
nImpacts = 1000
netParam="8 0 0 50 6 false"

[profiles.debug.batchscript.slurm_settings]
qos = "debug"
time_limit = 30

#
# Default production profile
#

[profiles.production.input.parameters]

[profiles.production.batchscript.slurm_settings]
